name: Count .cpp Files

on:
  push:
    branches:
      - main  # or the branch you want to track
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  count-cpp-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Count .cpp files
      id: count
      run: |
        count=$(find . -name "*.cpp" | wc -l)
        echo "count=$count" >> $GITHUB_ENV

    - name: Create badge
      run: |
        echo "{\"schemaVersion\": 1, \"label\": \"Overall Solved\", \"message\": \"$count\", \"color\": \"blue\"}" > badge.json

    - name: Check for changes
      id: check-changes
      run: |
        if git diff --exit-code --quiet badge.json; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push badge
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add badge.json
        git commit -m "Update .cpp file count badge"
        git push
